# Generated by Django 2.2.10 on 2020-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Certificate Title')),
                ('credential_id', models.TextField(verbose_name='Credential ID')),
                ('credential_url', models.URLField(verbose_name='Credential ID')),
                ('issuing_organization', models.CharField(max_length=100, verbose_name='Issuing Organization')),
                ('issue_date', models.DateTimeField(verbose_name='Issue Date')),
                ('certification_image', models.ImageField(upload_to='certificateimage')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client name')),
                ('description', models.TextField(verbose_name='Client Say')),
                ('image', models.ImageField(default='default.png', upload_to='clients')),
            ],
        ),
    ]
